### ISSUE TITLE
pip install error

### ISSUE THREAD

**Issue by jgngo** [jonparrott/Ferris-3-Skeleton#1]
I'm getting this error on OSX Yosemite. Anybody know how to correct?

pip install --pre -t lib -r requirements.txt

Running setup.py install for simplejson
    error: must supply either home or prefix/exec-prefix -- not both
    Complete output from command /usr/local/opt/python/bin/python2.7 -c "import setuptools, tokenize;__file__='/var/folders/8w/fy97b7ts5y10vg41dn6tqlgw0000gn/T/pip-build-NuvTvf/simplejson/setup.py';exec(compile(getattr(tokenize, 'open', open)(__file__).read().replace('\r\n', '\n'), __file__, 'exec'))" install --record /var/folders/8w/fy97b7ts5y10vg41dn6tqlgw0000gn/T/pip-JpQ1PL-record/install-record.txt --single-version-externally-managed --compile --home=/var/folders/8w/fy97b7ts5y10vg41dn6tqlgw0000gn/T/tmpm0MZqi:
    running install

    error: must supply either home or prefix/exec-prefix -- not both

**Comment by jgngo** [comment]
Oh, found the solution. It's because my python was from homebrew. I just needed to create a file in my home directory.

vi ~/.pydistutils.cfg

[install]
prefix=

https://github.com/Homebrew/homebrew/blob/master/share/doc/homebrew/Homebrew-and-Python.md

**Comment by jonparrott** [comment]
Yep. Known issue with Homebrew python. No idea why they won't fix it. Make sure to remove the ~/.pydistutils.cfg before you try to install any packages globally.
